### ISSUE TITLE
Not Passing Required Inputs Still Passed When it Should Fail

### ISSUE THREAD

**Issue by Justintime50** [InsonusK/get-latest-release#1]
Currently, not passing required fields only throws an unhandled promise rejection and should instead fail completely, the step using this action passed with flying colors even though it didn't do anything.

There should be try/catch logic or an upfront sanity check to ensure that required expected values are present and fail/exit if not.

```
Warning: Unexpected input(s) 'github_token', valid inputs are ['myToken', 'exclude_types', 'view_top']
2
Run InsonusK/get-latest-release@v1.0.1
6
(node:2373) UnhandledPromiseRejectionWarning: Error: Parameter token or opts.auth is required
7
    at Object.getAuthString (/home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1573:15)
8
    at Object.getOctokitOptions (/home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:2853:24)
9
    at Object.getOctokit (/home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1793:39)
10
    at /home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1489:32
11
    at Generator.next (<anonymous>)
12
    at /home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1466:71
13
    at new Promise (<anonymous>)
14
    at module.exports.47.__awaiter (/home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1462:12)
15
    at run (/home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1480:12)
16
    at Object.47 (/home/runner/work/_actions/InsonusK/get-latest-release/v1.0.1/dist/index.js:1539:1)
17
(node:2373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
18
(node:2373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Justintime50** [comment]
Clearly not a priority, closing.
